### ISSUE TITLE
TypeError: (0 , _reactApollo.getDataFromTree) is not a function

### ISSUE THREAD

**Issue by sedubois** [ads1018/next-apollo-example#2]
When using next Link, I get (see [code](https://github.com/sedubois/next-apollo-example/commit/3420ce8b57f9e4936578aad6ff187f1a9d2bc3e6)):

```js
TypeError: (0 , _reactApollo.getDataFromTree) is not a function
    at Function._callee$ (http://localhost:3000/_next/commons.js:27220:59)
```

Hitting ctrl-R solves the issue. Would you have any idea on the cause?

**Comment by sedubois** [comment]
I opened an issue on Next.js' side: https://github.com/zeit/next.js/issues/702

**Comment by ads1018** [comment]
ah good spot. I'm not sure but looks like react-apollo isn't getting extracted into the common bundle for some reason.

**Comment by ads1018** [comment]
@sedubois Figured out why. In react-apollo, the browser build deliberately doesn't feature the getDataFromTree or renderToStringWithData utilities because they're intended for server use only. See https://github.com/apollostack/react-apollo/issues/387#issuecomment-269915378

We can use `import { getDataFromTree } from 'react-apollo/lib/index` for now. Going to ask the folks over at Apollo if they have a more elegant solve. Would be nice if they could include that utility in the browser build...

**Comment by sedubois** [comment]
Thanks. In that case, shouldn't the fix be to wrap `getDataFromTree` into an `if(isServer)`? Why should the behaviour intended by Apollo be bypassed?

**Comment by sedubois** [comment]
Also, I adapted my app as you suggested (in [this branch](https://github.com/RelateNow/relate/compare/apollo-refactor)), and the page transitions are much slower than before. Maybe some store hydration issue or similar?

**Comment by ads1018** [comment]
@sedubois yup, wrapping `getDataFromTree` in an `if (isServer`) did the trick. I also had to change `initClient.js` a bit to fix the hydration issue you pointed out (I used the `with-redux` example on the next repo as a guide). Seems to work pretty great now! Let me know if you spot any more issues.
