### ISSUE TITLE
In Redux example, where to add auth related initialState?

### ISSUE THREAD

**Issue by jaydenseric** [ads1018/next-apollo-example#4]
I am not much of a Redux guru, so this is a real noodle-scratcher for me.

I have a cookie that holds the viewer's user ID and access token, populated by the results of a successful login mutation. Using a cookie so it will be available on the client and server for SSR, and will persist after closing the browser.

I figure Redux can be used to subscribe the UI on both the server and client to the viewer state. A logout action trashes the state and the cookie, hopefully with the UI updating without a page reload.

A search for `initialState` in the `redux` branch reveals 12 instances in 3 files. So where do you hydrate the viewer initial state from the cookie? How do you merge it in with the Apollo stuff?

Maybe there a way you can add initial state inside the Apollo state, that perfectly matches how the results from the `login` mutation gets cached.

**Comment by ads1018** [comment]
Hey @jaydenseric - not sure where you landed on this, but I put my own state (separate from apollo data) inside separately namespaced state trees. You can import as many reducers as you want inside the reducer file: https://github.com/ads1018/next-apollo-example/blob/redux/lib/reducer.js

So perhaps your state tree could look something like this:

```
state: {
  apollo: {
    ...
  },
  user: {
    ...
  }
}
```

Hope this helps. I would definitely confirm what's best practice when it comes to auth & Apollo inside the Apollo slack channel just to make sure this is kosher.

**Comment by jaydenseric** [comment]
Thanks, in the end I picked over everything until I understood it line by line. Then I refactored it into a single HoC file, and managed to reduce it down to ~150 lines – including auth stuff. There were a few little redundancies and SSR gotchas. It's naturally very confusing, as it's where Next.js/SSR, Apollo, Redux and auth collide in a single file - it took a few days and I had to thoroughly comment everything.

Once it's battle tested I'll publish it somehow.

**Comment by ads1018** [comment]
Cool - please do share :)

**Comment by natterstefan** [comment]
First of all, thanks @ads1018 for this helpful example. Very good to get to know some things around Apollo and nextjs. _But_ I am struggling ([like](https://github.com/apollographql/apollo-client/issues/2509) [some](https://github.com/apollographql/apollo-client/issues/2593) [others](https://github.com/apollographql/apollo-client/issues/2273)) to get Redux working with Apollo 2.0 again ([like this old example for instance](https://github.com/zeit/next.js/blob/master/examples/with-apollo-and-redux/lib/withData.js#L83)).

Do you know how to achieve this? Or other question: how can I update the state of the app (so that other components act accordingly), when it is not gql-query related, with Apollo 2.0 now (w/ or w/o Redux)? Hopefully you know more about this topic, as I am struggling for hours now...

@jaydenseric Have you solved it by now? You said you gonna "battel test" it and may be publish it. Is now the time to so so please? ;)

**Comment by jaydenseric** [comment]
@natterstefan I used it for a few months, then realised I didn't need Redux at all. I was only using it to track basic details about the logged in user ("viewer"). Turns out it is way more elegant and flexible to have a viewer query that resolves a `User` type or `null` if not logged in. That way in components you can query whatever you like about the viewer and you don't have to manually update state somewhere when logging in or out.

I still have my own `withData` decorator which is written differently to the Next.js examples, but ultimately works on similar principals.
